### PR TITLE
Patch 0.207.20 Items

### PR DESCRIPTION
**Pull request by Sanduhr32**
I hope i didn't miss any.

### CODE REVIEW

**Comment by jensbrak** [comment]
Nice! 

I believe you missed FistFenrirClaw.
Also missing in the main branch is the Root armor and some items connected to that.

I've done a PR too with all these items BUT also with a code change that loads the items from an external file instead of being hard coded. Not sure if it will be accepted tho.

**Comment by Sanduhr32** [comment]
Nice to have some feedback, yeah i didn't find the `FistFenrisClaw`. However some items are NPCs only & break inventory completely if you have them inside of your / chests inventory.

**Comment by jensbrak** [comment]
I have manufactured the FistFenrisClaw ingame - it's called "Flesh Ripper". So non-NPC item.
Same goes for the Root Armor set and the parts needed for it  (they're missing in the main branch).

**Comment by Sanduhr32** [comment]
Ah, I didn't see it yet ingame. I just assumed it's an NPC weapon that's not really obtainable

**Comment by Wufflez** [comment]
Hi, thanks for this update but I've added these items along with others today based on a rip of the current patch (0.207.20) so don't think this change is required.

At the moment this file is generated by a crappy semi automated processes that relies on unpacking the unity asset files from the game directory in steam and then running a script to generate this source file. I should probably clean the script up and make it less hard-coded so it doesn't require small changes on each patch to update some mono behaviour IDs to search for (e.g. needs the pickup ID to find items you can pick up etc) and add it to this repository for others to use.

There is another pull request open at the moment to allow having these loaded from a CSV file which I haven't had time to look through yet, but even for that it would be better to modify the script to build the CSV file from the real game data instead of just manually editing it each time.

Gonna close this for now, but re-open it if you spot an item from this frost cave patch that I missed.

**Pull request closed without merging**
