### PR TITLE
Features/minor updates

### PR DESCRIPTION
**Pull request by jensbrak**
Some minor updates, just for the fun of it:

- Moved to .NET 6
- Shared Item Database moved to CSV file and loaded at runtime 
- Added some missing items related to the addition of Abomination

Justifications:

- Opted for CSV format since it's both compact and flexible. The new ItemDb can be maintained directly in a spread sheet application and the format is widely supported by converters. Json might be the most obvious choice but is less compact and cannot be used in spreadsheets without some conversion first. SQL in some form adds unnecessary complexity and dependency to a database engine.
- Chosed to add the CSV parsing by using external package. CsvHelper has been around for a long time and is still being maintained. While a custom CSV parser is easy to write, this feels more reliable and results in much less code added.
- The database, now in CSV format, is included 'as is' (CSV format with .csv file extension). Might look a bit lame but if that's an issue one could consider using a custom extension (like .cdb or something) to make the file actually look like a db file. If that's an issue.
- I chose to load the file runtime and from external file. This way, the ItemDb can be updated without having to compile and release a new version of Loki. On the other hand, loading it runtime from external file could be seen as less solid.
- If that's an issue I see several options: one could be to embed the file as a resource. But why bother?

### CODE REVIEW

**Comment by jensbrak** [comment]
Added new items from last items, too.

**Comment by Wufflez** [comment]
Hi, sorry I haven't had chance to review this yet - March was a bit crazy for me and I was out of the country for a few weeks and not really able to get online much and then real life stuff got in the way for a while so I've only just got around to addressing the 'Frost Cave' update they rolled out (not even played it myself yet!)

I'm not opposed at all to loading the item definitions at load time from some external file like a .csv file.

Just FYI at the moment this SharedItemData.cs file itself is autogenerated by a fairly crappy script that rummages through the various .asset files I unpack from each big update to the game and spits out this file. It also tries to look up the various strings that start with $ to find resources in the localisation file e.g. "$item_*****" to get things like the Display name.

The script is a bit of a one-off and hard coded to things like paths on my system as well as requiring some GUIDs for certain mono behaviours used to identify items you can pick up for example, that need hand changing on each release because every time there's a change I always say 'I'll make some code to go find that ID value dynamically..... next time' and you know how those things are - it's always "next time"

What I think would be best is to change (or just re-make) my script to generate the CSV file instead of the SharedItemData.cs file - so that the source of information remains the same, but still allows users to edit it should they have some mods or want to suport an update before this tool gets updated.

**Comment by jensbrak** [comment]
Yeah, I kinda suspected that the file was generated. I ended up generating the attached .csv file using equally crappy scripting. The csv loading works just fine, been using it ever since now, without any hickups. Think I've added items for new version too. How you end up doing things doesn't really matter - for me it was more logical to write the code to read the csv rather than making a PR with the missing items directly. Can't say I am the quick fix guy all the time ;)

**Comment by jensbrak** [comment]
So is this script of yours updated?

If not, is it included in the relase to do a PR on, if this PR here is not of interest?

**Comment by Wufflez** [comment]
Hi, no it isn't updated I haven't even found it yet. This pull request is still of interest though as it's quite nice to have the data farmed out into a standalone file.

I think it's probably worth targeting .NET 7 now though as it's the current LTS version.

I am unfortunately a bit busy finishing off a load of work for real-work stuff before I finish for Christmas. I plan on winding down next week, though and probably have some time to get back on my gaming PC and update Valheim and figuire out what's what. They've changed so much since I played, including how the save files are handled plus their own backup system - need to figure out how all that works really. Looking forward to trying the game again as it's been so long. I'm guessing from the items and the name of the latest update that the Mistlands are finally completed and not just empty areas!

**Comment by jensbrak** [comment]
No worries. I'll update to .NET 7 and add whatever's been added to the game too. Same for me, I dropped the game for quite some time and am busy with work. The new mistland update got me back into it again.

**Comment by jensbrak** [comment]
Replaced by

https://github.com/Wufflez/Loki/pull/31

and

https://github.com/Wufflez/Loki/pull/32

**Pull request closed without merging**
